baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Max's ORL Blog"
theme = 'PaperMod'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[languages.en]
languageName = "English"
weight = 1

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[languages.en.menu.main]]
name = "Activity Log"
url = "log/"
weight = 5

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 10

[[languages.en.menu.main]]
name = "Photo Gallery"
url = "gallery/"
weight = 10

